# Generated by Django 2.1.1 on 2019-11-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('date', models.TextField()),
                ('retweets', models.IntegerField()),
                ('favorites', models.IntegerField()),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
    ]
