# Generated by Django 2.1.1 on 2019-11-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtweesaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='flag',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
