# Generated by Django 2.1.1 on 2019-11-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtweesaster', '0004_auto_20191120_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
